Fix grouped elements angle calculation issue
flux3dp/beam-studio pull request #67
Opened 2021-04-27 03:17 UTC by net5566

2021-04-27 03:51 UTC, dkdkwizard commented on public/js/lib/svgeditor/svgcanvas.js
> +                        var sangle = (gangle + cangle) % 360;
Angle needs to be bounded in -180 ~ 180.
```js
if (sangle > 180) {
  sangle -= 180;
} else if (sangle < -180) {
  sangle += 180;
}
```

2021-04-27 05:55 UTC, dkdkwizard requested changes
Tiny fix needed.

2021-04-29 06:28 UTC, dkdkwizard commented on public/js/lib/svgeditor/svgcanvas.js
> +              sangle += 180;
Should be 360.
Sorry, my bad.

2021-04-29 07:21 UTC, dkdkwizard approved these changes
+2

2021-04-29 07:26 UTC, ChenYanting approved these changes
LGTM

2021-05-03 10:09 UTC, merged